-- Hyprland Lua Configuration
-- Migrated from hyprland.conf

-- ======= Variables & Colors =======
local cachylgreen = "rgba(82dcccff)"
local cachymgreen = "rgba(00aa84ff)"
local cachydgreen = "rgba(007d6fff)"
local cachylblue = "rgba(01ccffff)"
local cachymblue = "rgba(182545ff)"
local cachydblue = "rgba(111826ff)"
local cachywhite = "rgba(ffffffff)"
local cachygrey = "rgba(ddddddff)"
local cachygray = "rgba(798bb2ff)"

local primary = "rgb(7aa2f7)"
local surface = "rgb(1a1b26)"
local secondary = "rgb(bb9af7)"
local error_color = "rgb(f7768e)"
local tertiary = "rgb(9ece6a)"
local surface_lowest = "rgb(1c1d2a)"

local mainMod = "SUPER"

-- ======= App Defaults =======
local ipc = "qs -c noctalia-shell ipc call"
local filemanager = "thunar"
local applauncher = "rofi -show drun -display-drun \"\" -show-icons"
local terminal = "alacritty"
local capturing = "grim -g \"$(slurp)\" - | swappy -f -"
local music = "spotify-launcher"
local passwordManager = "1password"
local webapp = "chromium --new-window --enable-features=UseOzonePlatform --ozone-plaftorm=wayland --app"
local launchOrFocus = "/home/antes/.config/hypr/scripts/launch-or-focus.sh"
local launchOrFocusInNewWindow = "/home/antes/.config/hypr/scripts/launch-on-new-workspace.sh"

-- ======= Environment Variables =======
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_CURSOR_SIZE", "24")

-- ======= General Configuration =======
hl.config({
  autogenerated = false,
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 3,
    col = {
      active_border = primary,
      inactive_border = surface,
    },
    layout = "dwindle",
    snap = {
      enabled = true,
    },
  },
  decoration = {
    active_opacity = 1.0,
    rounding = 20,
    rounding_power = 2,
    blur = {
      size = 3,
      passes = 2,
      xray = true,
      enabled = true,
      vibrancy = 0.1696,
    },
    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
      color = "rgba(1a1a1aee)",
    },
  },
  input = {
    follow_mouse = 2,
    float_switch_override_focus = 2,
  },
  group = {
    col = {
      border_active = secondary,
      border_inactive = surface,
      border_locked_active = error_color,
      border_locked_inactive = surface,
    },
    groupbar = {
      font_family = "Fira Sans",
      text_color = cachydblue,
      col = {
        active = secondary,
        inactive = surface,
        locked_active = error_color,
        locked_inactive = surface,
      },
    },
  },
  misc = {
    font_family = "Fira Sans",
    splash_font_family = "Fira Sans",
    disable_hyprland_logo = true,
    ["col.splash"] = cachylgreen,
    background_color = cachydblue,
    enable_swallow = true,
    swallow_regex = "^(cachy-browser|firefox|nautilus|nemo|thunar|btrfs-assistant.)$",
    focus_on_activate = true,
    vrr = 2,
  },
  render = {
    direct_scanout = true,
  },
  master = {
    new_status = "master",
    special_scale_factor = 0.8,
  },
  animations = {
    enabled = false,
  },
  binds = {
    allow_workspace_cycles = true,
    workspace_back_and_forth = true,
    workspace_center_on = true,
    movefocus_cycles_fullscreen = true,
    window_direction_monitor_fallback = true,
  },
})

-- ======= Monitors =======
hl.monitor({ output = "DP-2", mode = "2560x1440@164", position = "1920x0", scale = 1 })
hl.monitor({ output = "DP-3", mode = "1920x1080@164", position = "0x0", scale = 1 })

-- ======= Animations =======
hl.curve("overshot", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.1} } })

hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, bezier = "overshot", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 6, bezier = "overshot", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 6, bezier = "overshot", style = "slidefade 80%" })

-- ======= Window Rules =======
hl.window_rule({ match = { class = "org.pulseaudio.pavucontrol" }, float = true })
hl.window_rule({ match = { title = "^(Picture in picture)$" }, float = true })
hl.window_rule({ match = { title = "^(Save File)$" }, float = true })
hl.window_rule({ match = { title = "^(Open File)$" }, float = true })
hl.window_rule({ match = { class = "LibreWolf", title = "^(Picture-in-Picture)$" }, float = true })
hl.window_rule({ match = { class = "blueman-manager" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$" }, float = true })
hl.window_rule({ match = { class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$" }, float = true })
hl.window_rule({ match = { class = "^(CachyOSHello)$" }, float = true })
hl.window_rule({ match = { class = "^(zenity)$" }, float = true })
hl.window_rule({ match = { title = "^(Steam - Self Updater)$" }, float = true })

hl.window_rule({ match = { class = "^(thunar|nemo)$" }, opacity = 0.92 })
hl.window_rule({ match = { class = "^(discord|armcord|webcord)$" }, opacity = 0.96 })
hl.window_rule({ match = { title = "^(QQ|Telegram|AyuGram)$" }, opacity = 0.95, float = true })
hl.window_rule({ match = { title = "^(NetEase Cloud Music Gtk4)$" }, opacity = 0.95 })

hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, float = true })
hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, size = { 960, 540 } })
hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, move = { "25%", "25%" } })
hl.window_rule({ match = { title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$" }, float = true })
hl.window_rule({ match = { title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$" }, move = { "25%", "25%" } })
hl.window_rule({ match = { title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$" }, size = { 960, 540 } })
hl.window_rule({ match = { title = "^(danmufloat)$" }, pin = true })
hl.window_rule({ match = { title = "^(danmufloat|termfloat)$" }, rounding = 5 })
hl.window_rule({ match = { class = "^(kitty|Alacritty)$" }, animation = "slide right", workspace = "3" })
hl.window_rule({ match = { class = "^(org.mozilla.firefox)$" }, no_blur = true })
hl.window_rule({ match = { class = "^(zen)$" }, workspace = "1" })

hl.window_rule({ match = { float = true, workspace = "w[fv1-10]" }, border_size = 2 })
hl.window_rule({ match = { float = true, workspace = "w[fv1-10]" }, border_color = cachylblue })
hl.window_rule({ match = { float = true, workspace = "w[fv1-10]" }, rounding = 8 })

hl.window_rule({ match = { float = false, workspace = "f[1-10]" }, border_size = 3 })
hl.window_rule({ match = { float = false, workspace = "f[1-10]" }, rounding = 4 })
-- ======= Workspace Rules =======
hl.workspace_rule({ workspace = "w[tv1-10]", gaps_out = 1, gaps_in = 1 })
hl.workspace_rule({ workspace = "f[1]", gaps_out = 1, gaps_in = 1 })

-- ======= Layer Rules =======
hl.layer_rule({ match = { namespace = "logout_dialog" }, animation = "slide top" })
hl.layer_rule({ match = { namespace = "waybar" }, animation = "slide down" })
hl.layer_rule({ match = { namespace = "wallpaper" }, animation = "fade 50%" })

-- ======= Keybinds =======
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(launchOrFocusInNewWindow .. " Alacritty " .. terminal), { description = "Opens terminal" })
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(launchOrFocusInNewWindow .. " Discord discord"), { description = "Opens discord" })
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(launchOrFocus .. " Thunar " .. filemanager), { description = "Opens file manager" })
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(capturing), { description = "Screen capture" })
hl.bind(mainMod .. " + ESCAPE", hl.dsp.window.close(), { description = "Close window" })
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("loginctl terminate-user \"\""), { description = "Exit Hyprland" })
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle float" })
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = 0 }), { description = "Toggle fullscreen" })
hl.bind(mainMod .. " + Y", hl.dsp.window.pin(), { description = "Pin window" })
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(launchOrFocusInNewWindow .. " zen zen-browser"), { description = "Launch browser" })
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(webapp .. "=\"https://www.youtube.com\""), { description = "Open Youtube" })
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd(music), { description = "Open Spotify" })
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("AyuGram Desktop"), { description = "Open Telegram" })
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(ipc .. " launcher clipboard"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(ipc .. " launcher toggle"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(ipc .. " lockScreen lock"))

hl.bind(mainMod .. " + K", hl.dsp.group.toggle(), { description = "Toggle group" })
hl.bind(mainMod .. " + Tab", hl.dsp.group.next(), { description = "Next window in group" })

-- Volume
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5% && pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\\d+(?=%)' | awk '{if($1>100) system(\"pactl set-sink-volume @DEFAULT_SINK@ 100%\")}' && pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\\d+(?=%)' | awk '{print $1}' | head -1 > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob"), { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5% && pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\\d+(?=%)' | awk '{print $1}' | head -1 > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob"), { repeating = true, locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("amixer sset Master toggle | sed -En '/\\[on\\]/ s/.*\\[([0-9]+)%\\]/\\1/ p; /\\[off\\]/ s/.*/0/p' | head -1 > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob"), { repeating = true, locked = true })

-- Playback
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { description = "Play/Pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { description = "Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { description = "Prev track" })

-- Brightness
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +5%"), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"), { repeating = true, locked = true })

-- Window Movement
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Resizing
hl.bind(mainMod .. " + R", hl.dsp.submap("resize"), { description = "Resize mode" })
hl.define_submap("resize", function()
  hl.bind("right", hl.dsp.window.resize({ x = 15, y = 0 }), { repeating = true })
  hl.bind("left", hl.dsp.window.resize({ x = -15, y = 0 }), { repeating = true })
  hl.bind("up", hl.dsp.window.resize({ x = 0, y = -15 }), { repeating = true })
  hl.bind("down", hl.dsp.window.resize({ x = 0, y = 15 }), { repeating = true })
  hl.bind("l", hl.dsp.window.resize({ x = 15, y = 0 }), { repeating = true })
  hl.bind("h", hl.dsp.window.resize({ x = -15, y = 0 }), { repeating = true })
  hl.bind("k", hl.dsp.window.resize({ x = 0, y = -15 }), { repeating = true })
  hl.bind("j", hl.dsp.window.resize({ x = 0, y = 15 }), { repeating = true })
  hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + CTRL + SHIFT + right", hl.dsp.window.resize({ x = 15, y = 0 }))
hl.bind(mainMod .. " + CTRL + SHIFT + left", hl.dsp.window.resize({ x = -15, y = 0 }))
hl.bind(mainMod .. " + CTRL + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -15 }))
hl.bind(mainMod .. " + CTRL + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 15 }))

hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Workspaces
for i = 1, 9 do
  hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + CTRL + " .. i, hl.dsp.window.move({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i, silent = true }))
end
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + CTRL + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, silent = true }))

hl.bind(mainMod .. " + PERIOD", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + COMMA", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + slash", hl.dsp.focus({ workspace = "previous" }))

-- Special Workspaces
hl.bind(mainMod .. " + minus", hl.dsp.window.move({ workspace = "special" }))
hl.bind(mainMod .. " + equal", hl.dsp.workspace.toggle_special("special"))
hl.bind(mainMod .. " + F1", hl.dsp.workspace.toggle_special("scratchpad"))
hl.bind(mainMod .. " + ALT + SHIFT + F1", hl.dsp.window.move({ workspace = "special:scratchpad", silent = true }))

-- ======= Autostart =======
hl.on("hyprland.start", function()
  hl.exec_cmd("QT_QPA_PLATFORMTHEME=gtk3 qs -c noctalia-shell --no-duplicate")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("mako")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("bash -c \"mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown\"")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("thunar --daemon")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("systemctl --user import-environment")
  hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null")
  hl.exec_cmd("dbus-update-activation-environment --systemd")
  hl.exec_cmd("hypridle")
end)
