# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$ipc = qs -c noctalia-shell ipc call
$filemanager = thunar 
$applauncher = rofi -show drun -display-drun "" -show-icons
$terminal = alacritty
$capturing = grim -g "$(slurp)" - | swappy -f -
$music = spotify-launcher
$passwordManager = 1password
$webapp = chromium --new-window --enable-features=UseOzonePlatform --ozone-plaftorm=wayland --app
$launchOrFocus =  ~/.config/hypr/scripts/launch-or-focus.sh
